version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: superterminais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Porta externa 5433, interna 5432

  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: superterminais
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
    ports:
      - "8000:8000"
    command: sh -c "php artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
